/* AppAS Application for assignment 3 */

package Ex3;
//libraries
import Ex1.DataWIFI;
import Ex1.Location;
import Ex1.WIFI;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.text.NumberFormatter;

/**
 * Main window of the AppAS.
 */
public class AppAS extends JFrame {

    //define variables
    private final int limit=5;
    private final HelpFunctionEx3 hf=new HelpFunctionEx3();
    private final ReadFunctions rf=new ReadFunctions();
    private int flag=0;
    
    public static void main(String[] args)
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels=javax.swing.UIManager.getInstalledLookAndFeels();
            for (UIManager.LookAndFeelInfo installedLookAndFeel : installedLookAndFeels) {
                if ("Nimbus".equals(installedLookAndFeel.getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeel.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(new RunnableImpl());
    }
    /** Creates new form AppAS */
    public AppAS() 
    {
        
        initComponents();
        setIcon();
        pack();
        // Center in the screen
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(new Point((screenSize.width - frameSize.width) / 2,
                              (screenSize.height - frameSize.width) / 2));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupLogical = new javax.swing.ButtonGroup();
        buttonGroupTypeFilter = new javax.swing.ButtonGroup();
        jTabbedPanelTask = new javax.swing.JTabbedPane();
        jPanelALGO = new javax.swing.JPanel();
        jLabelSalgorithm = new javax.swing.JLabel();
        jLabelRow = new javax.swing.JLabel();
        jTextFieldRowTS = new javax.swing.JTextField();
        jButtonOKGPSTS = new javax.swing.JButton();
        jLabelMAC1 = new javax.swing.JLabel();
        jLabelMAC2 = new javax.swing.JLabel();
        jLabelMAC3 = new javax.swing.JLabel();
        jFormattedTextFieldMAC1 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldMAC2 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldMAC3 = new javax.swing.JFormattedTextField();
        jLabelSignal1 = new javax.swing.JLabel();
        jLabelSignal2 = new javax.swing.JLabel();
        jLabelSignal3 = new javax.swing.JLabel();
        jFormattedTextFieldSignal1 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldSignal2 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldSignal3 = new javax.swing.JFormattedTextField();
        jButtonOKThreeMAC = new javax.swing.JButton();
        jButtonFirstALGO = new javax.swing.JButton();
        jLabelFirstAlgorithm = new javax.swing.JLabel();
        jFormattedTextFieldMACfa = new javax.swing.JFormattedTextField();
        jLabelMACfa = new javax.swing.JLabel();
        jLabelLantitude = new javax.swing.JLabel();
        jLabelLongtitude = new javax.swing.JLabel();
        jLabelAltitude = new javax.swing.JLabel();
        jTextFieldLantitude = new javax.swing.JTextField();
        jTextFieldLongtitude = new javax.swing.JTextField();
        jTextFieldAltitude = new javax.swing.JTextField();
        jPanelIOput = new javax.swing.JPanel();
        jLabelAddFolder = new javax.swing.JLabel();
        jLabelAddFile = new javax.swing.JLabel();
        jLabelCB = new javax.swing.JLabel();
        jLabelSD = new javax.swing.JLabel();
        jLabelSK = new javax.swing.JLabel();
        jLabelShowData = new javax.swing.JLabel();
        jTextFieldNameFolder = new javax.swing.JTextField();
        jTextFieldNameFile = new javax.swing.JTextField();
        jTextFieldShowData = new javax.swing.JTextField();
        jTextFieldNameSaveFile = new javax.swing.JTextField();
        jTextFieldSaveKml = new javax.swing.JTextField();
        jButtonClearOK = new javax.swing.JButton();
        jButtonBrowseFolder = new javax.swing.JButton();
        jButtonOKFolder = new javax.swing.JButton();
        jButtonBrowseFile = new javax.swing.JButton();
        jButtonOKFile = new javax.swing.JButton();
        jButtonSaveFile = new javax.swing.JButton();
        jButtonSaveKML = new javax.swing.JButton();
        jButtonShowData = new javax.swing.JButton();
        jTextFieldFilter = new javax.swing.JTextField();
        jPanelFilters = new javax.swing.JPanel();
        jLabelTime = new javax.swing.JLabel();
        jFormattedTextFieldFROM = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTO = new javax.swing.JFormattedTextField();
        jLabelFROMTime = new javax.swing.JLabel();
        jLabelTOTime = new javax.swing.JLabel();
        jRadioButtonAnd = new javax.swing.JRadioButton();
        jRadioButtonOr = new javax.swing.JRadioButton();
        jRadioButtonNOTtime = new javax.swing.JRadioButton();
        jRadioButtonNotUse = new javax.swing.JRadioButton();
        jLabelAND = new javax.swing.JLabel();
        jLabelOR = new javax.swing.JLabel();
        jLabelNOT = new javax.swing.JLabel();
        jLabelUSE = new javax.swing.JLabel();
        jLabelLocation = new javax.swing.JLabel();
        jLabelX = new javax.swing.JLabel();
        //create a formatted location text field
        NumberFormat number = new DecimalFormat("###.########");
        jFormattedTextFieldLantitude = new javax.swing.JFormattedTextField(new NumberFormatter(number));
        jLabelY = new javax.swing.JLabel();
        jFormattedTextFieldLongtitude = new javax.swing.JFormattedTextField(new NumberFormatter(number));
        jRadioButtonTime = new javax.swing.JRadioButton();
        jRadioButtonLocation = new javax.swing.JRadioButton();
        jLabelRadius = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabelDevice = new javax.swing.JLabel();
        jTextFieldDeviceName = new javax.swing.JTextField();
        jRadioButtonDecvice = new javax.swing.JRadioButton();
        jButtonFilter = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonUPdate = new javax.swing.JButton();
        jRadioButtonNOTlocation = new javax.swing.JRadioButton();
        jRadioButtonNOTdevice = new javax.swing.JRadioButton();
        mainMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setTitle("AppWIFI");
        setMinimumSize(new java.awt.Dimension(660, 500));
        setPreferredSize(new java.awt.Dimension(660, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jTabbedPanelTask.setMinimumSize(new java.awt.Dimension(660, 480));
        jTabbedPanelTask.setPreferredSize(new java.awt.Dimension(660, 480));

        jPanelALGO.setBackground(new java.awt.Color(255, 204, 204));
        jPanelALGO.setMinimumSize(new java.awt.Dimension(660, 450));
        jPanelALGO.setPreferredSize(new java.awt.Dimension(660, 450));

        jLabelSalgorithm.setText("Second algorithm ");

        jLabelRow.setText("ROW");

        jTextFieldRowTS.setText("row as comb_no_gps_ts1.csv");

        jButtonOKGPSTS.setText("OK");
        jButtonOKGPSTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKGPSTSActionPerformed(evt);
            }
        });

        jLabelMAC1.setText("MAC");

        jLabelMAC2.setText("MAC");

        jLabelMAC3.setText("MAC");

        jFormattedTextFieldMAC1.setColumns(20);
        try {
            jFormattedTextFieldMAC1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("HH:HH:HH:HH:HH:HH")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldMAC1.setText("");
        jFormattedTextFieldMAC1.setMinimumSize(new java.awt.Dimension(150, 30));
        jFormattedTextFieldMAC1.setPreferredSize(new java.awt.Dimension(150, 30));

        jFormattedTextFieldMAC2.setColumns(20);
        try {
            jFormattedTextFieldMAC2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("HH:HH:HH:HH:HH:HH")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldMAC2.setText("");
        jFormattedTextFieldMAC2.setMinimumSize(new java.awt.Dimension(150, 30));
        jFormattedTextFieldMAC2.setPreferredSize(new java.awt.Dimension(150, 30));

        jFormattedTextFieldMAC3.setColumns(20);
        try {
            jFormattedTextFieldMAC3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("HH:HH:HH:HH:HH:HH")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldMAC3.setText("");
        jFormattedTextFieldMAC3.setMinimumSize(new java.awt.Dimension(150, 30));
        jFormattedTextFieldMAC3.setPreferredSize(new java.awt.Dimension(150, 30));

        jLabelSignal1.setText("Signal");

        jLabelSignal2.setText("Signal");

        jLabelSignal3.setText("Signal");

        jFormattedTextFieldSignal1.setColumns(4);
        jFormattedTextFieldSignal1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));

        jFormattedTextFieldSignal2.setColumns(4);
        jFormattedTextFieldSignal2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));

        jFormattedTextFieldSignal3.setColumns(4);
        jFormattedTextFieldSignal3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));

        jButtonOKThreeMAC.setText("OK");
        jButtonOKThreeMAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKThreeMACActionPerformed(evt);
            }
        });

        jButtonFirstALGO.setText("First algorithm");
        jButtonFirstALGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFirstALGOActionPerformed(evt);
            }
        });

        jLabelFirstAlgorithm.setText("First algorithm");

        jFormattedTextFieldMACfa.setColumns(20);
        try {
            jFormattedTextFieldMACfa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("HH:HH:HH:HH:HH:HH")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldMACfa.setText("11:22:33:44:55:66  ");

        jLabelMACfa.setText("MAC");

        jLabelLantitude.setText("Lantitude");

        jLabelLongtitude.setText("Longtitude");

        jLabelAltitude.setText("Altitude");

        jTextFieldLantitude.setEditable(false);

        jTextFieldLongtitude.setEditable(false);

        jTextFieldAltitude.setEditable(false);

        javax.swing.GroupLayout jPanelALGOLayout = new javax.swing.GroupLayout(jPanelALGO);
        jPanelALGO.setLayout(jPanelALGOLayout);
        jPanelALGOLayout.setHorizontalGroup(
            jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelALGOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonFirstALGO)
                    .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelALGOLayout.createSequentialGroup()
                            .addComponent(jLabelMAC2)
                            .addGap(18, 18, 18)
                            .addComponent(jFormattedTextFieldMAC2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addComponent(jLabelSalgorithm, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelRow, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonOKGPSTS, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelALGOLayout.createSequentialGroup()
                            .addComponent(jLabelMAC1)
                            .addGap(18, 18, 18)
                            .addComponent(jFormattedTextFieldMAC1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelALGOLayout.createSequentialGroup()
                            .addComponent(jLabelMAC3)
                            .addGap(18, 18, 18)
                            .addComponent(jFormattedTextFieldMAC3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelALGOLayout.createSequentialGroup()
                            .addComponent(jLabelMACfa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jFormattedTextFieldMACfa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelALGOLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabelLantitude)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelALGOLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldLantitude, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelLongtitude)
                    .addComponent(jTextFieldLongtitude, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelALGOLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelAltitude)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelALGOLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAltitude, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelALGOLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOKThreeMAC)
                .addGap(93, 93, 93))
            .addGroup(jPanelALGOLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTextFieldRowTS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelALGOLayout.createSequentialGroup()
                .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelALGOLayout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelALGOLayout.createSequentialGroup()
                                .addComponent(jLabelSignal1)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldSignal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelALGOLayout.createSequentialGroup()
                                .addComponent(jLabelSignal3)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldSignal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelALGOLayout.createSequentialGroup()
                                .addComponent(jLabelSignal2)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldSignal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelALGOLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelFirstAlgorithm)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelALGOLayout.setVerticalGroup(
            jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelALGOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSalgorithm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldRowTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOKGPSTS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMAC1)
                    .addComponent(jFormattedTextFieldMAC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSignal1)
                    .addComponent(jFormattedTextFieldSignal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMAC2)
                    .addComponent(jFormattedTextFieldMAC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSignal2)
                    .addComponent(jFormattedTextFieldSignal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMAC3)
                    .addComponent(jFormattedTextFieldMAC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSignal3)
                    .addComponent(jFormattedTextFieldSignal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOKThreeMAC))
                .addGap(18, 18, 18)
                .addComponent(jLabelFirstAlgorithm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldMACfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMACfa)
                    .addComponent(jLabelLongtitude)
                    .addComponent(jLabelLantitude)
                    .addComponent(jLabelAltitude))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAltitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLantitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLongtitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jButtonFirstALGO)
                .addGap(0, 98, Short.MAX_VALUE))
        );

        jTabbedPanelTask.addTab("Algo", jPanelALGO);
        jPanelALGO.getAccessibleContext().setAccessibleName("ALGO");

        jPanelIOput.setBackground(new java.awt.Color(204, 255, 255));
        jPanelIOput.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanelIOput.setMinimumSize(new java.awt.Dimension(660, 450));
        jPanelIOput.setPreferredSize(new java.awt.Dimension(660, 450));

        jLabelAddFolder.setText("Add Folder of Wigle files");

        jLabelAddFile.setText("Add wigle file");

        jLabelCB.setText("Clear database");

        jLabelSD.setText("Save the data in a special file");
        jLabelSD.setMinimumSize(new java.awt.Dimension(160, 14));
        jLabelSD.setPreferredSize(new java.awt.Dimension(160, 14));

        jLabelSK.setText("Save the database in kml format");
        jLabelSK.setMaximumSize(new java.awt.Dimension(180, 14));
        jLabelSK.setMinimumSize(new java.awt.Dimension(180, 14));
        jLabelSK.setPreferredSize(new java.awt.Dimension(180, 14));

        jLabelShowData.setText("Show data");

        jTextFieldNameFolder.setEditable(false);
        jTextFieldNameFolder.setColumns(25);
        jTextFieldNameFolder.setText("Name Folder");
        jTextFieldNameFolder.setMinimumSize(new java.awt.Dimension(55, 20));

        jTextFieldNameFile.setEditable(false);
        jTextFieldNameFile.setColumns(25);
        jTextFieldNameFile.setText("Name File ");
        jTextFieldNameFile.setMinimumSize(new java.awt.Dimension(55, 20));

        jTextFieldShowData.setEditable(false);
        jTextFieldShowData.setColumns(25);
        jTextFieldShowData.setText("Data:");
        jTextFieldShowData.setMinimumSize(new java.awt.Dimension(55, 20));

        jTextFieldNameSaveFile.setEditable(false);
        jTextFieldNameSaveFile.setColumns(25);
        jTextFieldNameSaveFile.setText("Save File");
        jTextFieldNameSaveFile.setMinimumSize(new java.awt.Dimension(55, 20));

        jTextFieldSaveKml.setEditable(false);
        jTextFieldSaveKml.setColumns(25);
        jTextFieldSaveKml.setText("KML File");
        jTextFieldSaveKml.setMinimumSize(new java.awt.Dimension(55, 20));

        jButtonClearOK.setText("Clear");
        jButtonClearOK.setToolTipText("");
        jButtonClearOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearOKActionPerformed(evt);
            }
        });

        jButtonBrowseFolder.setText("Browse");
        jButtonBrowseFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseFolderActionPerformed(evt);
            }
        });

        jButtonOKFolder.setText("OK");
        jButtonOKFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKFolderActionPerformed(evt);
            }
        });

        jButtonBrowseFile.setText("Browse");
        jButtonBrowseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseFileActionPerformed(evt);
            }
        });

        jButtonOKFile.setText("OK");
        jButtonOKFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKFileActionPerformed(evt);
            }
        });

        jButtonSaveFile.setText("Save");
        jButtonSaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveFileActionPerformed(evt);
            }
        });

        jButtonSaveKML.setText("Save");
        jButtonSaveKML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveKMLActionPerformed(evt);
            }
        });

        jButtonShowData.setText("Show");
        jButtonShowData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowDataActionPerformed(evt);
            }
        });

        jTextFieldFilter.setEditable(false);
        jTextFieldFilter.setColumns(50);
        jTextFieldFilter.setText("Filter:");

        javax.swing.GroupLayout jPanelIOputLayout = new javax.swing.GroupLayout(jPanelIOput);
        jPanelIOput.setLayout(jPanelIOputLayout);
        jPanelIOputLayout.setHorizontalGroup(
            jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIOputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIOputLayout.createSequentialGroup()
                        .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAddFile, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAddFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelShowData, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCB, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldSaveKml, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNameSaveFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNameFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNameFolder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldShowData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 22, Short.MAX_VALUE)
                        .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jButtonSaveKML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSaveFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBrowseFile, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jButtonBrowseFolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE))
                    .addGroup(jPanelIOputLayout.createSequentialGroup()
                        .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonShowData)
                            .addComponent(jTextFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonOKFolder, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(jButtonOKFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
            .addGroup(jPanelIOputLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jButtonClearOK)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelIOputLayout.setVerticalGroup(
            jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIOputLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddFolder)
                    .addComponent(jTextFieldNameFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBrowseFolder)
                    .addComponent(jButtonOKFolder))
                .addGap(29, 29, 29)
                .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddFile)
                    .addComponent(jTextFieldNameFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBrowseFile)
                    .addComponent(jButtonOKFile))
                .addGap(28, 28, 28)
                .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelIOputLayout.createSequentialGroup()
                        .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCB)
                            .addComponent(jButtonClearOK))
                        .addGap(30, 30, 30)
                        .addComponent(jLabelSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNameSaveFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSaveFile)))
                .addGap(27, 27, 27)
                .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIOputLayout.createSequentialGroup()
                        .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSaveKml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSaveKML))
                        .addGap(28, 28, 28)
                        .addComponent(jLabelShowData))
                    .addComponent(jTextFieldShowData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonShowData)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jButtonBrowseFolder.getAccessibleContext().setAccessibleName("jButtonBrowseFolder");

        jTabbedPanelTask.addTab("IOput", null, jPanelIOput, "");
        jPanelIOput.getAccessibleContext().setAccessibleName("IOput");

        jPanelFilters.setBackground(new java.awt.Color(255, 255, 204));
        jPanelFilters.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanelFilters.setMinimumSize(new java.awt.Dimension(660, 450));
        jPanelFilters.setPreferredSize(new java.awt.Dimension(660, 450));
        jPanelFilters.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanelFiltersAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabelTime.setText("Time");

        Date date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
        String dateString = formatter.format(date);
        jFormattedTextFieldFROM.setColumns(20);
        try {
            jFormattedTextFieldFROM.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-## ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldFROM.setText(dateString);

        jFormattedTextFieldTO.setColumns(20);
        try {
            jFormattedTextFieldTO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-## ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTO.setText(dateString);

        jLabelFROMTime.setText("FROM");

        jLabelTOTime.setText("TO");

        buttonGroupLogical.add(jRadioButtonAnd);

        buttonGroupLogical.add(jRadioButtonOr);
        jRadioButtonOr.setSelected(true);

        buttonGroupTypeFilter.add(jRadioButtonNOTtime);

        buttonGroupTypeFilter.add(jRadioButtonNotUse);
        jRadioButtonNotUse.setSelected(true);

        jLabelAND.setText("AND");

        jLabelOR.setText("OR");

        jLabelNOT.setText("NOT");

        jLabelUSE.setText("Not Use");

        jLabelLocation.setText("Location");

        jLabelX.setText("lantitude");

        jFormattedTextFieldLantitude.setColumns(18);
        jFormattedTextFieldLantitude.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###.#############"))));
        jFormattedTextFieldLantitude.setText("###.#############");
        jFormattedTextFieldLantitude.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldLantitudeKeyTyped(evt);
            }
        });

        jLabelY.setText("longitude");

        jFormattedTextFieldLongtitude.setColumns(18);
        jFormattedTextFieldLongtitude.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###.#############"))));
        jFormattedTextFieldLongtitude.setText("###.#############");
        jFormattedTextFieldLongtitude.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldLongtitudeKeyTyped(evt);
            }
        });

        buttonGroupTypeFilter.add(jRadioButtonTime);

        buttonGroupTypeFilter.add(jRadioButtonLocation);

        jLabelRadius.setText("Radius");

        jFormattedTextField1.setColumns(8);
        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0.0000"))));
        jFormattedTextField1.setText("0,03");
        jFormattedTextField1.setMinimumSize(new java.awt.Dimension(8, 20));

        jLabelDevice.setText("Device");

        jTextFieldDeviceName.setText("device name");

        buttonGroupTypeFilter.add(jRadioButtonDecvice);

        jButtonFilter.setText("Filter");
        jButtonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonUPdate.setText("UPdate");
        jButtonUPdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUPdateActionPerformed(evt);
            }
        });

        buttonGroupTypeFilter.add(jRadioButtonNOTlocation);

        buttonGroupTypeFilter.add(jRadioButtonNOTdevice);

        javax.swing.GroupLayout jPanelFiltersLayout = new javax.swing.GroupLayout(jPanelFilters);
        jPanelFilters.setLayout(jPanelFiltersLayout);
        jPanelFiltersLayout.setHorizontalGroup(
            jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFiltersLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabelAND)
                            .addComponent(jRadioButtonAnd))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jRadioButtonOr)
                            .addComponent(jLabelOR))
                        .addGap(185, 185, 185)
                        .addComponent(jLabelUSE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanelFiltersLayout.createSequentialGroup()
                        .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDeviceName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelFiltersLayout.createSequentialGroup()
                                .addComponent(jLabelFROMTime, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jFormattedTextFieldFROM, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelTOTime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldTO, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelFiltersLayout.createSequentialGroup()
                                .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelX)
                                    .addComponent(jLabelRadius))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelFiltersLayout.createSequentialGroup()
                                        .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButtonUPdate)
                                            .addGroup(jPanelFiltersLayout.createSequentialGroup()
                                                .addComponent(jFormattedTextFieldLantitude, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabelY)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextFieldLongtitude, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)))
                .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jRadioButtonDecvice)
                    .addComponent(jRadioButtonNotUse)
                    .addComponent(jRadioButtonLocation)
                    .addComponent(jRadioButtonTime))
                .addGap(35, 35, 35)
                .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jRadioButtonNOTdevice)
                    .addComponent(jRadioButtonNOTlocation)
                    .addComponent(jRadioButtonNOTtime)
                    .addComponent(jLabelNOT))
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(jPanelFiltersLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDevice)
                    .addComponent(jLabelLocation)
                    .addComponent(jLabelTime))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelFiltersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonFilter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancel)
                .addGap(99, 99, 99))
        );

        jPanelFiltersLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jRadioButtonDecvice, jRadioButtonLocation, jRadioButtonNOTdevice, jRadioButtonNOTlocation, jRadioButtonNOTtime, jRadioButtonNotUse, jRadioButtonTime});

        jPanelFiltersLayout.setVerticalGroup(
            jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTime)
                    .addComponent(jLabelNOT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFiltersLayout.createSequentialGroup()
                        .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAND)
                            .addComponent(jLabelOR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonOr)
                            .addComponent(jRadioButtonAnd)))
                    .addGroup(jPanelFiltersLayout.createSequentialGroup()
                        .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFiltersLayout.createSequentialGroup()
                                .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jFormattedTextFieldFROM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jFormattedTextFieldTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelFROMTime)
                                        .addComponent(jLabelTOTime))
                                    .addComponent(jRadioButtonNOTtime))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelLocation))
                            .addComponent(jRadioButtonTime, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFiltersLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelX)
                                    .addComponent(jFormattedTextFieldLantitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelY)
                                    .addComponent(jFormattedTextFieldLongtitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelRadius)
                                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelDevice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldDeviceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelFiltersLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButtonLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonNOTlocation))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonDecvice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonNOTdevice, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(22, 22, 22)
                        .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButtonNotUse)
                            .addComponent(jLabelUSE))
                        .addGap(7, 7, 7)))
                .addGap(27, 27, 27)
                .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFilter)
                    .addComponent(jButtonUPdate)
                    .addComponent(jButtonCancel))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jPanelFiltersLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jRadioButtonDecvice, jRadioButtonNOTdevice, jRadioButtonNOTlocation, jRadioButtonNOTtime, jRadioButtonNotUse, jRadioButtonTime});

        jTabbedPanelTask.addTab("Filter", jPanelFilters);
        jPanelFilters.getAccessibleContext().setAccessibleName("Filters");

        getContentPane().add(jTabbedPanelTask, java.awt.BorderLayout.PAGE_START);
        jTabbedPanelTask.getAccessibleContext().setAccessibleName("TabbedPanels");

        fileMenu.setMnemonic('F');
        fileMenu.setText("File");

        aboutMenuItem.setMnemonic('A');
        aboutMenuItem.setText("About");
        aboutMenuItem.setToolTipText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(aboutMenuItem);

        exitMenuItem.setMnemonic('E');
        exitMenuItem.setText("Exit");
        exitMenuItem.setToolTipText("Quit Team, Quit!");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        mainMenu.add(fileMenu);

        setJMenuBar(mainMenu);
        mainMenu.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        new About(this).setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jFormattedTextFieldLantitudeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldLantitudeKeyTyped
       if(jFormattedTextFieldLantitude.getText().length()>=limit &&
                        evt.getKeyChar()!= KeyEvent.VK_BACK_SPACE &&
                        evt.getKeyChar()== KeyEvent.VK_DELETE)
                    evt.consume();
    }//GEN-LAST:event_jFormattedTextFieldLantitudeKeyTyped

    private void jFormattedTextFieldLongtitudeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldLongtitudeKeyTyped
        if(jFormattedTextFieldLongtitude.getText().length()>=limit &&
                        evt.getKeyChar()!= KeyEvent.VK_BACK_SPACE &&
                        evt.getKeyChar()== KeyEvent.VK_DELETE)
                    evt.consume();
    }//GEN-LAST:event_jFormattedTextFieldLongtitudeKeyTyped
  //this function writes database in kml format
    private void jButtonSaveKMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveKMLActionPerformed
        String str=hf.SaveKML();
        jTextFieldSaveKml.setText(str);
    }//GEN-LAST:event_jButtonSaveKMLActionPerformed
    //the functon show data about number of WiFi and rows in database
    private void jButtonShowDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowDataActionPerformed
        jTextFieldShowData.setText(hf.ShowData());
        jTextFieldFilter.setText(hf.ShowFilter());
    }//GEN-LAST:event_jButtonShowDataActionPerformed
    //the function cleaning database
    private void jButtonClearOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearOKActionPerformed
        hf.Clear();
    }//GEN-LAST:event_jButtonClearOKActionPerformed
    //the function browse a folder with the Wigle files
    private void jButtonBrowseFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseFolderActionPerformed
        jTextFieldNameFolder.setText(hf.BrowseFolder());
    }//GEN-LAST:event_jButtonBrowseFolderActionPerformed
    //the function browse the Wigle file
    private void jButtonBrowseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseFileActionPerformed
        jTextFieldNameFile.setText(hf.BrowseFile());
    }//GEN-LAST:event_jButtonBrowseFileActionPerformed
    //the function save special file
    private void jButtonSaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveFileActionPerformed
        jTextFieldNameSaveFile.setText(hf.SaveFile());
    }//GEN-LAST:event_jButtonSaveFileActionPerformed
    //the function add data from wigle file to database
    private void jButtonOKFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKFileActionPerformed
        hf.AddFile(jTextFieldNameFile.getText());
    }//GEN-LAST:event_jButtonOKFileActionPerformed
    //the function add data from wigle folder to database
    private void jButtonOKFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKFolderActionPerformed
        hf.AddFolder(jTextFieldNameFolder.getText());
    }//GEN-LAST:event_jButtonOKFolderActionPerformed
    //the function makes the first algorithm
    private void jButtonFirstALGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFirstALGOActionPerformed
        Location lla=hf.FirstAlgorithm(jFormattedTextFieldMACfa.getText());
        jTextFieldLantitude.setText(String.valueOf(lla.getLat()));
        jTextFieldLongtitude.setText(String.valueOf(lla.getLon()));
        jTextFieldAltitude.setText(String.valueOf(lla.getAlt()));
    }//GEN-LAST:event_jButtonFirstALGOActionPerformed
    //the function makes the second algorithms for 3 mac
    private void jButtonOKThreeMACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKThreeMACActionPerformed
        //variables
        ArrayList<DataWIFI> dwf=new ArrayList<>();
        DataWIFI ThreeMAC=new DataWIFI();
        Location place=new Location();
        WIFI tmp1=new WIFI();   WIFI tmp2=new WIFI();   WIFI tmp3=new WIFI();
        if (tmp1.setMAC(jFormattedTextFieldMAC1.getText().toLowerCase())==1)
        {
            if (tmp1.setSignal(Integer.parseInt(jFormattedTextFieldSignal1.getText()))==1)
                ThreeMAC.setWiFi(tmp1);
        }
        if (tmp2.setMAC(jFormattedTextFieldMAC2.getText().toLowerCase())==1)
        {
            if (tmp2.setSignal(Integer.parseInt(jFormattedTextFieldSignal2.getText()))==1)
                ThreeMAC.setWiFi(tmp2);
        }
        if (tmp3.setMAC(jFormattedTextFieldMAC3.getText().toLowerCase())==1)
        {
            if (tmp3.setSignal(Integer.parseInt(jFormattedTextFieldSignal3.getText()))==1)
                ThreeMAC.setWiFi(tmp3);
        }
        dwf=rf.ReadDataBase();
        place=hf.ThreeMac(dwf,ThreeMAC);
        jTextFieldLantitude.setText(String.valueOf(place.getLat()));
        jTextFieldLongtitude.setText(String.valueOf(place.getLon()));
        jTextFieldAltitude.setText(String.valueOf(place.getAlt()));
    }//GEN-LAST:event_jButtonOKThreeMACActionPerformed
    //the function uses the second algotithm for row as comb_no_gps_ts1.csv
    private void jButtonOKGPSTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKGPSTSActionPerformed
        //variables
        String str=jTextFieldRowTS.getText();
        ArrayList<DataWIFI> dwf=new ArrayList<>();
        Location place=new Location();
        dwf=rf.ReadDataBase();
        place=hf.RowTS(dwf,str);
        jTextFieldLantitude.setText(String.valueOf(place.getLat()));
        jTextFieldLongtitude.setText(String.valueOf(place.getLon()));
        jTextFieldAltitude.setText(String.valueOf(place.getAlt()));
    }//GEN-LAST:event_jButtonOKGPSTSActionPerformed
    //the function make filter
    private void jButtonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterActionPerformed
        if (flag==0)
        {
            
            System.out.println("1");
            flag++;
        }
        else
            if (flag==1)
            {
                System.out.println("2");
                flag++;
            }
            else
            {
                System.out.println("only 2");
            }
    }//GEN-LAST:event_jButtonFilterActionPerformed
    //the function back 
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        if (flag!=0)
            flag--;
        else
            System.out.println("no filters");
    }//GEN-LAST:event_jButtonCancelActionPerformed
    //filter panel is selected
    private void jPanelFiltersAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanelFiltersAncestorAdded
        flag=0;
    }//GEN-LAST:event_jPanelFiltersAncestorAdded

   //the function update database
    private void jButtonUPdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUPdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUPdateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.ButtonGroup buttonGroupLogical;
    private javax.swing.ButtonGroup buttonGroupTypeFilter;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton jButtonBrowseFile;
    private javax.swing.JButton jButtonBrowseFolder;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClearOK;
    private javax.swing.JButton jButtonFilter;
    private javax.swing.JButton jButtonFirstALGO;
    private javax.swing.JButton jButtonOKFile;
    private javax.swing.JButton jButtonOKFolder;
    private javax.swing.JButton jButtonOKGPSTS;
    private javax.swing.JButton jButtonOKThreeMAC;
    private javax.swing.JButton jButtonSaveFile;
    private javax.swing.JButton jButtonSaveKML;
    private javax.swing.JButton jButtonShowData;
    private javax.swing.JButton jButtonUPdate;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextFieldFROM;
    private javax.swing.JFormattedTextField jFormattedTextFieldLantitude;
    private javax.swing.JFormattedTextField jFormattedTextFieldLongtitude;
    private javax.swing.JFormattedTextField jFormattedTextFieldMAC1;
    private javax.swing.JFormattedTextField jFormattedTextFieldMAC2;
    private javax.swing.JFormattedTextField jFormattedTextFieldMAC3;
    private javax.swing.JFormattedTextField jFormattedTextFieldMACfa;
    private javax.swing.JFormattedTextField jFormattedTextFieldSignal1;
    private javax.swing.JFormattedTextField jFormattedTextFieldSignal2;
    private javax.swing.JFormattedTextField jFormattedTextFieldSignal3;
    private javax.swing.JFormattedTextField jFormattedTextFieldTO;
    private javax.swing.JLabel jLabelAND;
    private javax.swing.JLabel jLabelAddFile;
    private javax.swing.JLabel jLabelAddFolder;
    private javax.swing.JLabel jLabelAltitude;
    private javax.swing.JLabel jLabelCB;
    private javax.swing.JLabel jLabelDevice;
    private javax.swing.JLabel jLabelFROMTime;
    private javax.swing.JLabel jLabelFirstAlgorithm;
    private javax.swing.JLabel jLabelLantitude;
    private javax.swing.JLabel jLabelLocation;
    private javax.swing.JLabel jLabelLongtitude;
    private javax.swing.JLabel jLabelMAC1;
    private javax.swing.JLabel jLabelMAC2;
    private javax.swing.JLabel jLabelMAC3;
    private javax.swing.JLabel jLabelMACfa;
    private javax.swing.JLabel jLabelNOT;
    private javax.swing.JLabel jLabelOR;
    private javax.swing.JLabel jLabelRadius;
    private javax.swing.JLabel jLabelRow;
    private javax.swing.JLabel jLabelSD;
    private javax.swing.JLabel jLabelSK;
    private javax.swing.JLabel jLabelSalgorithm;
    private javax.swing.JLabel jLabelShowData;
    private javax.swing.JLabel jLabelSignal1;
    private javax.swing.JLabel jLabelSignal2;
    private javax.swing.JLabel jLabelSignal3;
    private javax.swing.JLabel jLabelTOTime;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jLabelUSE;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JLabel jLabelY;
    private javax.swing.JPanel jPanelALGO;
    private javax.swing.JPanel jPanelFilters;
    private javax.swing.JPanel jPanelIOput;
    private javax.swing.JRadioButton jRadioButtonAnd;
    private javax.swing.JRadioButton jRadioButtonDecvice;
    private javax.swing.JRadioButton jRadioButtonLocation;
    private javax.swing.JRadioButton jRadioButtonNOTdevice;
    private javax.swing.JRadioButton jRadioButtonNOTlocation;
    private javax.swing.JRadioButton jRadioButtonNOTtime;
    private javax.swing.JRadioButton jRadioButtonNotUse;
    private javax.swing.JRadioButton jRadioButtonOr;
    private javax.swing.JRadioButton jRadioButtonTime;
    private javax.swing.JTabbedPane jTabbedPanelTask;
    private javax.swing.JTextField jTextFieldAltitude;
    private javax.swing.JTextField jTextFieldDeviceName;
    private javax.swing.JTextField jTextFieldFilter;
    private javax.swing.JTextField jTextFieldLantitude;
    private javax.swing.JTextField jTextFieldLongtitude;
    private javax.swing.JTextField jTextFieldNameFile;
    private javax.swing.JTextField jTextFieldNameFolder;
    private javax.swing.JTextField jTextFieldNameSaveFile;
    private javax.swing.JTextField jTextFieldRowTS;
    private javax.swing.JTextField jTextFieldSaveKml;
    private javax.swing.JTextField jTextFieldShowData;
    private javax.swing.JMenuBar mainMenu;
    // End of variables declaration//GEN-END:variables
    //the function set icon to JFrame
    private void setIcon()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("WiFi.jpg")));
    }

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }
        @Override
        public void run()
        {
            new AppAS().setVisible(true);
        }
    }
}
